CREATE TABLE PROGRAM (
    IDT_PROGRAM BIGINT PRIMARY KEY DEFAULT unique_rowid(),
    COD_PROGRAM UUID NOT NULL DEFAULT gen_random_uuid(),

    IDT_ENTERPRISE BIGINT NOT NULL,
    IDT_PROGRAM_TYPE BIGINT NOT NULL,

    DES_TITLE VARCHAR(200) NOT NULL,
    DES_JOB_DESCRIPTION STRING,
    DES_REQUIREMENTS STRING,
    DES_DIFFERENCES STRING,
    DES_BENEFITS STRING,

    DAT_CREATED_AT TIMESTAMP NOT NULL DEFAULT now(),
    DAT_UPDATED_AT TIMESTAMP NULL,

    CONSTRAINT UK_PROGRAM_COD UNIQUE (COD_PROGRAM),

    CONSTRAINT FK_PROGRAM_ENTERPRISE
        FOREIGN KEY (IDT_ENTERPRISE)
        REFERENCES ENTERPRISE (IDT_ENTERPRISE),

    CONSTRAINT FK_PROGRAM_TYPE
        FOREIGN KEY (IDT_PROGRAM_TYPE)
        REFERENCES PROGRAM_TYPE (IDT_PROGRAM_TYPE)
);

CREATE INDEX IDX_PROGRAM_ENTERPRISE ON PROGRAM (IDT_ENTERPRISE);
CREATE INDEX IDX_PROGRAM_TYPE ON PROGRAM (IDT_PROGRAM_TYPE);